### ISSUE TITLE
[BUG] user 화면에서 채용공고 입력하기 선택 이후 자동으로 예상 질문 받아보기가 선택되는 오류

### ISSUE THREAD

**Issue by yeh-jeans** [boostcampaitech6/level2-3-nlp-finalproject-nlp-04#25]
## 🐛 Bug Report

- JD 부분 클릭 후  다른 버튼의 좌측 공백을 클릭하면 넘어가집니다

## 📝 To do 
- [ ] user 부분 코드 변경하기

## Screenshos

희찬스 왕감사
![image](https://github.com/boostcampaitech6/level2-3-nlp-finalproject-nlp-04/assets/69586041/d1c7b407-a816-4b9c-9092-ad7bd0df449f)

**Comment by kooqooo** [comment]
방금 시도해봤는데 오류가 발생하지 않더라고요. 버그 재현하는 방법 다음 회의에 설명부탁드려요.

**Comment by yeh-jeans** [comment]
그거 JD 클릭하시고 배경화면 아무곳이나 클릭하면 자동으로 예상질문 확인하기가 선택됩니다. 한번 더 해보시겠어요?

**Comment by yeh-jeans** [comment]
padding-left 를 margin-left 로 변경하여 해결
shout out to 관옥님
